baseurl = "http://cigarplug.ml/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Mohit Sainani"
title = "Technocracy"
disqusshortname = ""
pluralizelisttitles = false
googleAnalytics = "UA-112087825-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 IST"
description = "A blog by Mohit Sainani"
copyright = "Copyright © 2017 Mohit Sainani"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"

progressively = true
share = true
latestpostcount = 5
github = "cigarplug"
email = "ghost@cigarplug.ml"
# linkedin = "john-example-aa80ue8è"
# twitter = "example"
# facebook = "facebook_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false


# [params.colors]
# identifier = "#527fc1f"
# identifier_dark = "#1a3152"
# trivial = "#6a7a8b"
# foreground = "#181d2a"
# background = "#f9f9f9"
# background_dark = "#282a36"
# code = "#87a5d2"
# type = "#97d28b"
# special = "#ffcb8d"
# value = "#96c2d7"
# statement = "#ff8e91"
